#! /bin/bash

# Declare destination dir for AllTest in 
# one place so it is easy to modify
REPO=$GIT_HOME/prog270-song-2016

# Declare destination for CSS, JavaScript and Images
CSS_JS_IMAGE=$REPO/ApacheHelpers

# Copy AllTest
#if [ -d "$REPO/AllTest/" ]; then
#rm -rf $REPO/AllTest
#fi
cp -ruvp ~/Documents/AllTest $REPO/.

# Ensure destination dir exists for CSS, JS and Images
if [ ! -d "$CSS_JS_IMAGE" ]; then
    mkdir -p $CSS_JS_IMAGE
fi

# Copy CSS, JavaScript and Images
#if [ -d "$CSS_JS_IMAGE/css/" ]; then
#rm -rf $CSS_JS_IMAGE/css
#fi
#if [ -d "$CSS_JS_IMAGE/images/" ]; then
#rm -rf $CSS_JS_IMAGE/images
#fi
#if [ -d "$CSS_JS_IMAGE/js/" ]; then
#rm -rf $CSS_JS_IMAGE/js
#fi
cp -ruvp /var/www/html/css $CSS_JS_IMAGE/.
cp -ruvp /var/www/html/images $CSS_JS_IMAGE/.
cp -ruvp /var/www/html/js $CSS_JS_IMAGE/.

# Copy index.html
cp -uvp /var/www/html/index.html $REPO/.
