#! /bin/bash

# Declare destination dir for AllTest in 
# one place so it is easy to modify
REPO=$GIT_HOME/prog270-song-2016

# Declare destination for CSS, JavaScript and Images
CSS_JS_IMAGE=$REPO/ApacheHelpers

# Copy AllTest
#if [ -d "~/Documents/AllTest/" ]; then
#rm -rf ~/Documents/AllTest
#fi
cp -r $REPO/AllTest ~/Documents/.

# Clean up existing file
#if [ -d "/var/www/html/css/" ]; then
#rm -rf /var/www/html/css
#fi
#if [ -d "/var/www/html/images/" ]; then
#rm -rf /var/www/html/images
#fi
#if [ -d "/var/www/html/js/" ]; then
#rm -rf /var/www/html/js
#fi

# Ensure destination dir exists for CSS, JS and Images
#mkdir -p /var/www/html/css
#mkdir -p /var/www/html/images
#mkdir -p /var/www/html/js

# Copy CSS, JavaScript and Images
cp -ruvp $CSS_JS_IMAGE/css /var/www/html/.
cp -ruvp $CSS_JS_IMAGE/images /var/www/html/.
cp -ruvp $CSS_JS_IMAGE/js /var/www/html/.

# Copy index.html
cp -uvp $REPO/index.html /var/www/html/.

cp -uvp $REPO/scripts/.bash_aliases ~/.
cp -uvp $REPO/scripts/mixins.jade ~/Source/MakeHtml/node_modules/elven-site-tools/views/.
